/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2022-06-20 17:26:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.DB;
import java.sql.*;
import java.sql.*;

public final class bill_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("    <title>patient_Profile | Health Record</title>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- core CSS -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/prettyPhoto.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"css/main.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"jquery1.min\"></script>\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("    <script src=\"js/html5shiv.js\"></script>\r\n");
      out.write("    <script src=\"js/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->       \r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"images/ico/favicon.ico\">\r\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\" href=\"images/ico/apple-touch-icon-144-precomposed.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" sizes=\"114x114\" href=\"images/ico/apple-touch-icon-114-precomposed.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\" href=\"images/ico/apple-touch-icon-72-precomposed.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" href=\"images/ico/apple-touch-icon-57-precomposed.png\">\r\n");
      out.write(" <!-- <script>\r\n");
      out.write("        function myfun(){\r\n");
      out.write("         \r\n");
      out.write("            var d=document.getElementById(\"myid\").value;\r\n");
      out.write("            var fid = document.getElementById(\"fid\").value;\r\n");
      out.write("            alert(\"Requested Successfully !!!\");\r\n");
      out.write("          \r\n");
      out.write("                 \r\n");
      out.write("           $.ajax({url:\"prof_patient?id=\"+d+\"&fid=\"+fid,success:function(data,ResponseText){\r\n");
      out.write("                 \r\n");
      out.write("           }});\r\n");
      out.write("      \r\n");
      out.write("                   // window.location.href=\"prof_patient.jsp?id=\"+d+\"&fid=\"+fid;\r\n");
      out.write("                      //$(\"#myload\").load(\"prof_patient.jsp?id=\"+d+\"&fid=\"+fid);\r\n");
      out.write("            \r\n");
      out.write("             \r\n");
      out.write("              \r\n");
      out.write("         \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function myfun2(){\r\n");
      out.write("            var sid = document.getElementById(\"fid\").value;\r\n");
      out.write("            window.location.href=\"requests.jsp?sid=\"+sid;\r\n");
      out.write("      \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("    </script> -->\r\n");
      out.write("    <style>\r\n");
      out.write("    table{\r\n");
      out.write("    \tmargin-left: 239px;\r\n");
      out.write("    }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <header id=\"header\">\r\n");
      out.write("        <div class=\"top-bar\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-sm-6 col-xs-4\">\r\n");
      out.write("                        <div class=\"top-number\"><p><i class=\"fa fa-phone-square\"></i>  +0123 456 70 90</p></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-sm-6 col-xs-8\">\r\n");
      out.write("                       <div class=\"social\">\r\n");
      out.write("                            <ul class=\"social-share\">\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-linkedin\"></i></a></li> \r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-dribbble\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-skype\"></i></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <div class=\"search\">\r\n");
      out.write("                                <form role=\"form\">\r\n");
      out.write("                                    <input type=\"text\" class=\"search-form\" autocomplete=\"off\" placeholder=\"Search\">\r\n");
      out.write("                                    <i class=\"fa fa-search\"></i>\r\n");
      out.write("                                    \r\n");
      out.write("                                    \r\n");
      out.write("                                </form>\r\n");
      out.write("                           </div>\r\n");
      out.write("                       </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div><!--/.container-->\r\n");
      out.write("        </div><!--/.top-bar-->\r\n");
      out.write("\r\n");
      out.write("        <nav class=\"navbar navbar-inverse\" role=\"banner\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"navbar-header\">\r\n");
      out.write("                    <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("                        <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <a class=\"navbar-brand\" href=\"index.html\"><img src=\"images/logo.jpg\" alt=\"logo\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                <div class=\"collapse navbar-collapse navbar-right\">\r\n");
      out.write("                    <ul class=\"nav navbar-nav\">\r\n");
      out.write("                        \r\n");
      out.write("                         \r\n");
      out.write("                       \t<li><a href=\"patient1.jsp\">Profile</a></li>  \r\n");
      out.write("                       \t<li><a href=\"availtime.jsp\">Doctors Available Time</a></li>\r\n");
      out.write("                         <li><a href=\"index.html\">Logout</a></li>                           \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div><!--/.container-->\r\n");
      out.write("        </nav><!--/nav-->\r\n");
      out.write("\t</header><!--/header-->\r\n");
      out.write("\t\t\t<section id=\"about-us\" >\r\n");
      out.write("         \r\n");
      out.write("       \r\n");
      out.write("    \r\n");
      out.write("  <p>&nbsp;</p>\r\n");
      out.write("  <p>&nbsp;</p>\r\n");
      out.write("  \r\n");
      out.write("  <p>&nbsp;</p>\r\n");
      out.write("  <p>&nbsp;</p>\r\n");
      out.write("  ");

        String sess =(String)session.getAttribute("id");
        int id = Integer.parseInt(sess);
        
        Statement st = null;
        Connection cn = null;
        try{
            st= DB.control();
            ResultSet rs = st.executeQuery("select * from billing where id="+id+"");
            System.out.println(id);
           if(rs.next()){
        	   System.out.println("dsvs");
         
          
      out.write("  \r\n");
      out.write("\r\n");
      out.write("<table border=\"2\">\r\n");
      out.write("<tr>\r\n");
      out.write("<th>Pateint Id</th>\r\n");
      out.write("<th>Name</th>\r\n");
      out.write("<th>Birth</th>\r\n");
      out.write("<th>Address</th>\r\n");
      out.write("<th>Contact</th>\r\n");
      out.write("<th>Emasil</th>\r\n");
      out.write("<th>Gender</th>\r\n");
      out.write("<th>Disease</th>\r\n");
      out.write("<th>Consulted Doctor</th>\r\n");
      out.write("<th>BedCharge</th>\r\n");
      out.write("<th>Medicine Charge</th>\r\n");
      out.write("<th>Others Charge</th>\r\n");
      out.write("<th>TOtal</th>\r\n");
      out.write("</tr>\r\n");
      out.write("\t\r\n");
      out.write("         <tr>\r\n");
      out.write("           <td><b>");
      out.print(rs.getString(1) );
      out.write("</b></td>\r\n");
      out.write("        \r\n");
      out.write("             <td>");
      out.print(rs.getString(2) );
      out.write("</td>\r\n");
      out.write("           \r\n");
      out.write("              <td>");
      out.print(rs.getString(3) );
      out.write("</td>\r\n");
      out.write("             \r\n");
      out.write("             \r\n");
      out.write("               <td>");
      out.print(rs.getString(4) );
      out.write("</td>\r\n");
      out.write("              \r\n");
      out.write("                <td>");
      out.print(rs.getString(5) );
      out.write("</td>\r\n");
      out.write("     \r\n");
      out.write("               <td> ");
      out.print(rs.getString(6) );
      out.write("</td>\r\n");
      out.write("                 <td>");
      out.print(rs.getString(7) );
      out.write("</td>\r\n");
      out.write("                 <td> ");
      out.print(rs.getString(8) );
      out.write("</td>\r\n");
      out.write("                   <td>");
      out.print(rs.getString(9) );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print(rs.getString(10) );
      out.write("</td>\r\n");
      out.write("                     <td>");
      out.print(rs.getString(11) );
      out.write("</td>\r\n");
      out.write("                      <td>");
      out.print(rs.getString(12) );
      out.write("</td>\r\n");
      out.write("                       <td>");
      out.print(rs.getString(13) );
      out.write(" </td>\r\n");
      out.write("                              </tr>\r\n");
      out.write("          \r\n");
      out.write("    </table>\r\n");
      out.write("          ");
  
        }
           else
        	   
           {
        	   System.out.println("hello");
        	   
      out.write("\r\n");
      out.write("        \t   <center><h3 style=\"color:red;\">Bill is not yet generated</h3></center>\r\n");
      out.write("        \t   ");

        	  
           }
        }  
        catch(Exception e){
        	e.printStackTrace();
        }
    
      out.write("\r\n");
      out.write("        </section><!--/about-us-->\r\n");
      out.write("       \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <script src=\"js/jquery.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        $('.carousel').carousel()\r\n");
      out.write("    </script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.prettyPhoto.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.isotope.min.js\"></script>\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("    <script src=\"js/wow.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
