/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2022-06-20 17:28:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.DB;
import java.sql.*;
import java.sql.*;

public final class doc_005fprofile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"author\" content=\"\">\n");
      out.write("    <title>Patient Update | Health Record</title>\n");
      out.write("\t\n");
      out.write("\t<!-- core CSS -->\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"css/font-awesome.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"css/prettyPhoto.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"css/animate.min.css\" rel=\"stylesheet\">\n");
      out.write("\t<link href=\"css/main.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"css/responsive.css\" rel=\"stylesheet\">\n");
      out.write("    <script src=\"jquery1.min\"></script>\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("    <script src=\"js/html5shiv.js\"></script>\n");
      out.write("    <script src=\"js/respond.min.js\"></script>\n");
      out.write("    <![endif]-->       \n");
      out.write("    <link rel=\"shortcut icon\" href=\"images/ico/favicon.ico\">\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\" href=\"images/ico/apple-touch-icon-144-precomposed.png\">\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" sizes=\"114x114\" href=\"images/ico/apple-touch-icon-114-precomposed.png\">\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\" href=\"images/ico/apple-touch-icon-72-precomposed.png\">\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" href=\"images/ico/apple-touch-icon-57-precomposed.png\">\n");
      out.write("    <script>\n");
      out.write("    \tfunction myfun(){\n");
      out.write("    \t\t\n");
      out.write("    \t\t\n");
      out.write("    \t\talert(\"Updated Successfully !!!\");\n");
      out.write("    \t\twindow.location.href=\"patient_update.jsp\";\n");
      out.write("    \t}\n");
      out.write("    </script>\n");
      out.write("</head><!--/head-->\n");
      out.write("\n");

        String sess =(String)session.getAttribute("id");
        int id = Integer.parseInt(sess);
        
        Statement st = null;
        Connection cn = null;
        try{
            st= DB.control();
            ResultSet rs = st.executeQuery("select * from doctor where id="+id+"");
            rs.next();
            
       
      out.write("\n");
      out.write("  \n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <header id=\"header\">\n");
      out.write("        <div class=\"top-bar\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-sm-6 col-xs-4\">\n");
      out.write("                        <div class=\"top-number\"><p><i class=\"fa fa-phone-square\"></i>  +0123 456 70 90</p></div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-sm-6 col-xs-8\">\n");
      out.write("                       <div class=\"social\">\n");
      out.write("                            <ul class=\"social-share\">\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-linkedin\"></i></a></li> \n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-dribbble\"></i></a></li>\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-skype\"></i></a></li>\n");
      out.write("                            </ul>\n");
      out.write("                            <div class=\"search\">\n");
      out.write("                                <form role=\"form\">\n");
      out.write("                                    <input type=\"text\" class=\"search-form\" autocomplete=\"off\" placeholder=\"Search\">\n");
      out.write("                                    <i class=\"fa fa-search\"></i>\n");
      out.write("                                </form>\n");
      out.write("                           </div>\n");
      out.write("                       </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div><!--/.container-->\n");
      out.write("        </div><!--/.top-bar-->\n");
      out.write("\n");
      out.write("        <nav class=\"navbar navbar-inverse\" role=\"banner\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"navbar-header\">\n");
      out.write("                    <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\n");
      out.write("                        <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("                        <span class=\"icon-bar\"></span>\n");
      out.write("                        <span class=\"icon-bar\"></span>\n");
      out.write("                        <span class=\"icon-bar\"></span>\n");
      out.write("                    </button>\n");
      out.write("                    <a class=\"navbar-brand\" href=\"index.html\"><img src=\"images/logo.jpg\" alt=\"logo\"></a>\n");
      out.write("                </div>\n");
      out.write("\t\t\t\t\n");
      out.write("                <div class=\"collapse navbar-collapse navbar-right\">\n");
      out.write("                    <ul class=\"nav navbar-nav\">\n");
      out.write("                        \n");
      out.write("                       \n");
      out.write("                        <li><a href=\"doctor1.jsp\">Patient</a></li>\n");
      out.write("                        <li><a href=\"patient_update.jsp\">Update Patient</a></li> \n");
      out.write("                        <li class=\"active\"><a href=\"doc_profile.jsp\">My Profile</a></li>\n");
      out.write("                         <li><a href=\"index.html\">Logout</a></li>                           \n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div><!--/.container-->\n");
      out.write("        </nav><!--/nav-->\n");
      out.write("\t</header><!--/header-->\n");
      out.write("\n");
      out.write("    <section id=\"about-us\" >\n");
      out.write("        <form name=\"form1\"  method=\"post\" action=\"doc_profile\" onSubmit=\"return valid(this)\" >\n");
      out.write("            <input name=\"id\" type=\"hidden\" value='");
      out.print(rs.getInt(1));
      out.write("'/>\n");
      out.write("         <table  width=\"381\" border=\"2\" align=\"center\" cellpadding=\"2\" cellspacing=\"2\">\n");
      out.write("          \n");
      out.write("             \n");
      out.write("             <tr><td width=\"165\"><div align=\"center\"><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>Name</strong></em></font></div></td><td><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>");
      out.print(rs.getString(2));
      out.write("</strong></em></font></td><td rowspan=\"5\"><img src='images/photos/doctor/");
      out.print(rs.getString(11));
      out.write("' width=\"200px\" height=\"200px\"/></td></tr>\n");
      out.write("            <tr><td width=\"165\"><div align=\"center\"><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>Specialization</strong></em></font></div></td><td><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>");
      out.print(rs.getString(3));
      out.write("</strong></em></font></td></tr>\n");
      out.write("            <tr><td width=\"165\"><div align=\"center\"><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>DOB</strong></em></font></div></td><td><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>");
      out.print(rs.getString(4));
      out.write("</strong></em></font></td></tr>\n");
      out.write("            <tr><td width=\"165\"><div align=\"center\"><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>Address</strong></em></font></div></td><td><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>");
      out.print(rs.getString(5));
      out.write("</strong></em></font></td></tr>\n");
      out.write("            <tr><td width=\"165\"><div align=\"center\"><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>Contact</strong></em></font></div></td><td><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>");
      out.print(rs.getString(6));
      out.write("</strong></em></font></td></tr>\n");
      out.write("            <tr><td width=\"165\"><div align=\"center\"><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>Email</strong></em></font></div></td><td><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>");
      out.print(rs.getString(7));
      out.write("</strong></em></font></td></tr>\n");
      out.write("            <tr><td width=\"165\"><div align=\"center\"><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>Gender</strong></em></font></div></td><td><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>");
      out.print(rs.getString(8));
      out.write("</strong></em></font></td></tr>\n");
      out.write("            <tr><td width=\"165\"><div align=\"center\"><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>Available Time</strong></em></font></div></td><td><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong><input name=\"time\" type=\"time\" id=\"time\" value='");
      out.print(rs.getString(9));
      out.write("'/></strong></em></font></td></tr>\n");
      out.write("            <tr><td width=\"165\"><div align=\"center\"><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>Treatment</strong></em></font></div></td><td><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>");
      out.print(rs.getString(10));
      out.write("</strong></em></font></td></tr>\n");
      out.write("        </table> \n");
      out.write("        <table width=\"347\" border=\"0\" align=\"center\" cellpadding=\"2\" cellspacing=\"2\">\n");
      out.write("    <tr> \n");
      out.write("      <td height=\"31\"> <div align=\"center\"><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong> \n");
      out.write("          <input type=\"submit\" name=\"Submit\" value=\"Submit\" onclick=\"myfun()\">\n");
      out.write("          </strong></em></font></div></td>\n");
      out.write("    </tr>\n");
      out.write("        </table>\n");
      out.write("        </form>\n");
      out.write("        </section><!--/about-us-->\n");
      out.write("       \n");
      out.write("        ");

         }
        catch(Exception e){
            System.out.println(e);
        }
        
        
      
        
    
      out.write("\n");
      out.write("    \n");
      out.write("\n");
      out.write("    <script src=\"js/jquery.js\"></script>\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("        $('.carousel').carousel()\n");
      out.write("    </script>\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"js/jquery.prettyPhoto.js\"></script>\n");
      out.write("    <script src=\"js/jquery.isotope.min.js\"></script>\n");
      out.write("    <script src=\"js/main.js\"></script>\n");
      out.write("    <script src=\"js/wow.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
