/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2022-06-20 17:27:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.DB;
import java.sql.*;

public final class doctor2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");

        String id1 = request.getParameter("id");
        System.out.println(id1);
        int id = Integer.parseInt(id1);
        Statement st = null;
        try{
            st = DB.control();
            ResultSet rs = st.executeQuery("select * from patient where id = "+id+"");
            rs.next();
        
        
      out.write("\n");
      out.write("        <table>\n");
      out.write("        <tr>\n");
      out.write("        <td>  <img src='images/photos/patient/");
      out.print(rs.getString(13));
      out.write("' width=\"200px\" height=\"200px\" style=\"border:4px solid purple;border-radius:100px;float:left\"/></td>\n");
      out.write("        <td><br/>\n");
      out.write("        </td>\n");
      out.write("         </tr>\n");
      out.write("        </table>\n");
      out.write("      \n");
      out.write("    \n");
      out.write("       <br>\n");
      out.write("       <br>\n");
      out.write("        <table  width=\"381\" border=\"2\" align=\"center\" cellpadding=\"2\" cellspacing=\"2\" style=\"float:left;\">\n");
      out.write("       \n");
      out.write("            <tr><td width=\"165\"><div align=\"center\"><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>ID</strong></em></font></div></td><td><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>");
      out.print(rs.getInt(1));
      out.write("</strong></em></font></tr>\n");
      out.write("            <tr><td width=\"165\"><div align=\"center\"><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>Name</strong></em></font></div></td><td><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>");
      out.print(rs.getString(2));
      out.write("</strong></em></font></td></tr>\n");
      out.write("            <tr><td width=\"165\"><div align=\"center\"><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>DOB</strong></em></font></div></td><td><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>");
      out.print(rs.getString(3));
      out.write("</strong></em></font></td></tr>\n");
      out.write("            <tr><td width=\"165\"><div align=\"center\"><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>Address</strong></em></font></div></td><td><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>");
      out.print(rs.getString(4));
      out.write("</strong></em></font></td></tr>\n");
      out.write("            <tr><td width=\"165\"><div align=\"center\"><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>Contact</strong></em></font></div></td><td><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>");
      out.print(rs.getString(5));
      out.write("</strong></em></font></td></tr>\n");
      out.write("            <tr><td width=\"165\"><div align=\"center\"><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>Email</strong></em></font></div></td><td><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>");
      out.print(rs.getString(6));
      out.write("</strong></em></font></td></tr>\n");
      out.write("            <tr><td width=\"165\"><div align=\"center\"><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>Gender</strong></em></font></div></td><td><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>");
      out.print(rs.getString(7));
      out.write("</strong></em></font></td></tr>\n");
      out.write("            <tr><td width=\"165\"><div align=\"center\"><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>Disease</strong></em></font></div></td><td><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>");
      out.print(rs.getString(8));
      out.write("</strong></em></font></td></tr>\n");
      out.write("            <tr><td width=\"165\"><div align=\"center\"><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>Consulted Doctor</strong></em></font></div></td><td><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>");
      out.print(rs.getString(9));
      out.write("</strong></em></font></td></tr>\n");
      out.write("            <tr><td width=\"165\"><div align=\"center\"><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>Prescribed Medicine</strong></em></font></div></td><td><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>");
      out.print(rs.getString(10));
      out.write("</strong></em></font></td></tr>\n");
      out.write("            <tr><td width=\"165\"><div align=\"center\"><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>Current Condition</strong></em></font></div></td><td><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>");
      out.print(rs.getString(11));
      out.write("</strong></em></font></td></tr>\n");
      out.write("            <tr><td width=\"165\"><div align=\"center\"><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>Duration</strong></em></font></div></td><td><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>");
      out.print(rs.getString(12));
      out.write("</strong></em></font></td></tr>\n");
      out.write("            <tr><td width=\"165\"><div align=\"center\"><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>CurrentReport</strong></em></font></div></td><td><font size=\"5\" face=\"Times New Roman, Times, serif\"><em><strong>");
      out.print(rs.getString(14));
      out.write("</strong></em></font></td></tr>\n");
      out.write("        </table>\n");
      out.write("        &nbsp;  &nbsp;  &nbsp;  &nbsp;\n");
      out.write("        <table style=\"float:left;margin-left:35px\">\n");
      out.write("        <tr>\n");
      out.write("        <td>   Scanning Reports</td>\n");
      out.write("      \n");
      out.write("         </tr>\n");
      out.write("          <tr>\n");
      out.write("        <td>       <img src='images/photos/patient/");
      out.print(rs.getString(17));
      out.write("' width=\"200px\" height=\"200px\"/></td>\n");
      out.write("      \n");
      out.write("         </tr>\n");
      out.write("        </table>\n");
      out.write("    \n");
      out.write("                ");

                               }
                               catch(Exception e){
                                   System.out.println(e);
                                 }
                
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
